modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]


modId="moreoffhandslots"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config = "moreoffhandslots.mixins.json"

[[dependencies.moreoffhandslots]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.moreoffhandslots]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.moreoffhandslots]]
modId="curios"
mandatory=true
versionRange="[1.21.1-9.3.1,)"
ordering="AFTER"
side="BOTH"
